#%RAML 1.0 Library
usage: Schema for a Widget
uses:
  api: jsonApiLibrary.raml
types:
  widgets:
    type: api.resource
    description: a widget's primary data
    properties:
      attributes:
        properties:
          name:
            required: true
            type: string
            description: catalog name
          qty:
            required: false
            type: integer
            minimum: 0
            description: quantity
      relationships:
        type: WidgetRelationships
        required: false
    additionalProperties: false
    example:
      type: widgets
      id: abc-123
      attributes:
        name: can opener
        qty: 42
      relationships:
        location:
          data: 
            - type: Location
              id: "14"     
            - type: Location
              id: "15"
          links:
            self: /widgets/abc-123/relationships/location
  WidgetRelationships:
    type: object
    description: |
      A widget's relationships: 
        - location
    properties:
      location:
        type: api.relationshipMember
        description: location in inventory
        required: false
    example:
      location:
        data: 
          - type: locations
            id: "14"     
          - type: locations
            id: "15"
        links:
          self: /widgets/abc-123/relationships/location