#%RAML 1.0 NamedExample
value:
  links:
    self: /locations/123
  data: 
    type: Location
    id: "123"
    attributes:
      warehouse: Briarcliff Manor
      aisle: "45"
      shelf: "33"
      bin: "1"
