#%RAML 1.0 NamedExample
value:
  links:
    self: /widgets?filter[Location.warehouse]=Briarcliff+Manor,Secaucus&filter[Widget.name]=foobar&sort=-Widget.name
  data: 
    - type: Widget
      id: "123"
      attributes:
        name: "foobar"
    - type: Widget
      id: "14"
      attributes:
        name: "can opener"
        qty: 47
        locations:
          - type: Location
            id: "10510"
            attributes:
              warehouse: Briarcliff Manor
              aisle: "45"
              shelf: "33"
              bin: "1"
          - type: Location
            id: "333"
            attributes:
              warehouse: Secaucus
              aisle: "1"
              shelf: "1"
              bin: "1"