#%RAML 1.0 NamedExample
value:
  links:
    self: /widgets?filter[widgets.name]=can+opener,foobar
  data: 
    - type: widgets
      id: "123"
      attributes:
        name: "foobar"
      relationships:
        location:
          data: 
            - type: locations
              id: "1"
          links:
            self: /widgets/123/relationships/location
    - type: widgets
      id: "14"
      attributes:
        name: "can opener"
        qty: 47
      relationships:
        location:
          data: 
            - type: locations
              id: "1234"     
            - type: locations
              id: "1235"
          links:
            self: /widgets/14/relationships/location
