#%RAML 1.0 NamedExample
value:
  links:
    self: /widgets?filter[widgets.name]=can+opener,foo+bar
  data: 
    - type: widgets
      id: "123"
      attributes:
        name: "foo bar"
      relationships:
        locations:
          data: 
            - type: locations
              id: "1"
          links:
            self: /widgets/123/relationships/locations
        manufacturer:
          data:
            type: companies
            id: "aaa-122"
    - type: widgets
      id: "14"
      attributes:
        name: "can opener"
        qty: 47
      relationships:
        locations:
          data: 
            - type: locations
              id: "1234"     
            - type: locations
              id: "1235"
          links:
            self: /widgets/14/relationships/locations
        manufacturer:
          data:
            type: companies
            id: "abc123"
          links:
            self: /widgets/14/relationships/manufacturer
  included:
    - type: locations
      id: "1234"
      attributes:
        warehouse: Briarcliff Manor
        aisle: "45"
        shelf: "33"
        bin: "1"
      links:
        self: /locations/1234
    - type: locations
      id: "1235"
      attributes:
        warehouse: NYC
        aisle: "4"
        shelf: "3"
        bin: "12"      
      links:
        self: /locations/1235
    - type: companies
      id: "abc123"
      attributes:
        name: "ACME Manufacturing, Inc."
      links:
        self: /companies/abc123