#%RAML 1.0 NamedExample
value:
  links:
    self: /widgets/abc-123
  data: 
    type: Widget
    id: "abc-123"
    attributes:
      name: "can opener"
      qty: 47
    relationships:
      location:
        data: 
          - type: Location
            id: "1234"     
          - type: Location
            id: "1235"
        links:
          self: /widgets/abc-123/relationships/location